version: '2.0'
services:
  elastalert-ci:
    build: .
    volumes:
    - ./:/data
    depends_on:
    - "elasticsearch"
    environment:
    - "ES_HOST=elasticsearch"
    - "SKIP_SSL_VERIFY=1"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
    - "9200"
    - "9300"
    environment:
    - "discovery.type=single-node"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
